### PR TITLE
Add additional Dockerfiles and configs to use with docker-compose

### PR DESCRIPTION
**Pull request by ecliptik**
Verified and tested locally when using `docker-compose up` and Goldfish UI was accessible at http://localhost:8080.

example output of `docker-compose up` when running the stack and accessing it via a browser.

```
docker-compose up                                                                                                                                [69/1915]
Creating docker_vault_1
Creating docker_goldfish_1
Creating docker_goldfish-frontend_1
Attaching to docker_vault_1, docker_goldfish_1, docker_goldfish-frontend_1
vault_1              | ==> Vault server configuration:
vault_1              |
vault_1              |                      Cgo: disabled
vault_1              |          Cluster Address: https://0.0.0.0:8201
vault_1              |               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
vault_1              |                Log Level: info
vault_1              |                    Mlock: supported: true, enabled: false
vault_1              |         Redirect Address: http://0.0.0.0:8200
vault_1              |                  Storage: inmem
vault_1              |                  Version: Vault v0.7.3
vault_1              |              Version Sha: 0b20ae0b9b7a748d607082b1add3663a28e31b68
vault_1              |
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
vault_1              | 2017/06/23 05:58:21.553980 [INFO ] core: security barrier not initialized
100    18    0     0  100    18      0   3735 --:--:-- --:--:-- --:--:--  4500
vault_1              | 2017/06/23 05:58:21.554365 [INFO ] core: security barrier initialized: shares=1 threshold=1
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
vault_1              | 2017/06/23 05:58:21.554507 [INFO ] core: post-unseal setup starting
vault_1              | 2017/06/23 05:58:21.565039 [INFO ] core: loaded wrapping token key
vault_1              | 2017/06/23 05:58:21.568078 [INFO ] core: successfully mounted backend: type=generic path=secret/
vault_1              | 2017/06/23 05:58:21.568096 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault_1              | 2017/06/23 05:58:21.568180 [INFO ] core: successfully mounted backend: type=system path=sys/
vault_1              | 2017/06/23 05:58:21.568359 [INFO ] rollback: starting rollback manager
vault_1              | 2017/06/23 05:58:21.569132 [INFO ] expiration: restoring leases
vault_1              | 2017/06/23 05:58:21.571304 [INFO ] core: post-unseal setup complete
vault_1              | 2017/06/23 05:58:21.571476 [INFO ] core: root token generated
vault_1              | 2017/06/23 05:58:21.571483 [INFO ] core: pre-seal teardown starting
vault_1              | 2017/06/23 05:58:21.571499 [INFO ] core: cluster listeners not running
100    18    0     0  100    18      0   6893 --:--:-- --:--:-- --:--:-- 18000
vault_1              | 2017/06/23 05:58:21.571517 [INFO ] rollback: stopping rollback manager
vault_1              | 2017/06/23 05:58:21.571561 [INFO ] core: pre-seal teardown complete
vault_1              | 2017/06/23 05:58:21.571637 [INFO ] core: vault is unsealed
vault_1              | 2017/06/23 05:58:21.571666 [INFO ] core: post-unseal setup starting
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
vault_1              | 2017/06/23 05:58:21.571720 [INFO ] core: loaded wrapping token key
vault_1              | 2017/06/23 05:58:21.571853 [INFO ] core: successfully mounted backend: type=generic path=secret/
100   225    0     0  100   225      0   152k --:--:-- --:--:-- --:--:--  219k
vault_1              | ==> WARNING: Dev mode is enabled!
vault_1              |
vault_1              | In this mode, Vault is completely in-memory and unsealed.
vault_1              | Vault is configured to only have a single unseal key. The root
vault_1              | token has already been authenticated with the CLI, so you can
vault_1              | immediately begin using the Vault CLI.
vault_1              |
vault_1              | The only step you need to take is to set the following
vault_1              | environment variables:
vault_1              |
vault_1              |     export VAULT_ADDR='http://0.0.0.0:8200'
vault_1              |
vault_1              | The unseal key and root token are reproduced below in case you
vault_1              | want to seal/unseal the Vault or play with authentication.
vault_1              |
vault_1              | Unseal Key: LSSPrCHY/ixySakn7Kp5SbAt0c3g+4PCzTE7AWK+0kM=
vault_1              | Root Token: goldfish
vault_1              |
vault_1              | ==> Vault server started! Log data will stream in below:
vault_1              |
vault_1              | 2017/06/23 05:58:21.571928 [INFO ] core: successfully mounted backend: type=system path=sys/
vault_1              | 2017/06/23 05:58:21.571945 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault_1              | 2017/06/23 05:58:21.572092 [INFO ] rollback: starting rollback manager
vault_1              | 2017/06/23 05:58:21.572412 [INFO ] expiration: restoring leases
vault_1              | 2017/06/23 05:58:21.572769 [INFO ] core: post-unseal setup complete
vault_1              | 2017/06/23 05:58:22.127321 [INFO ] core: successful mount: path=transit/ type=transit
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
vault_1              | 2017/06/23 05:58:22.133197 [INFO ] core: enabled credential backend: path=approle/ type=approle
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
100   122    0     0  100   122      0  38006 --:--:-- --:--:-- --:--:-- 61000
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
100    22    0     0  100    22      0  13025 --:--:-- --:--:-- --:--:-- 22000
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
100   178    0     0  100   178      0  73130 --:--:-- --:--:-- --:--:--  173k
goldfish_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
goldfish_1           |                                  Dload  Upload   Total   Spent    Left  Speed
100   228  100   228    0     0  46644      0 --:--:-- --:--:-- --:--:-- 57000
goldfish_1           | 2017/06/23 05:58:22 [INFO ]: Server token accessor: e0eb5905-f25b-2ba0-ce21-1803211bf28d
goldfish_1           | 2017/06/23 05:58:22 Goldfish config reloaded
goldfish_1           | Goldfish version: v0.4.0
goldfish_1           | Goldfish successfully bootstrapped to vault
goldfish_1           |
goldfish_1           |   .
goldfish_1           |   ...             ...
goldfish_1           |   .........       ......
goldfish_1           |    ...........   ..........
goldfish_1           |      .......... ...............
goldfish_1           |      .............................
goldfish_1           |       .............................
goldfish_1           |          ...........................
goldfish_1           |         ...........................
goldfish_1           |         ..........................
goldfish_1           |         ...... ..................
goldfish_1           |       ......    ...............
goldfish_1           |      ..        ..      ....
goldfish_1           |     .                 ..
goldfish_1           |
goldfish_1           |
goldfish_1           | ⇛ http server started on [::]:8000
goldfish-frontend_1  | 172.19.0.1 - - [23/Jun/2017:06:00:52 +0000] "GET /api/login/csrf HTTP/1.1" 200 20 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4" "-"
goldfish_1           | {"time":"2017-06-23T06:00:52.377168792Z","remote_ip":"172.19.0.1","host":"localhost","method":"GET","uri":"/api/login/csrf","status":200, "latency":84,"latency_human":"84.699µs","bytes_in":0,"bytes_out":20}
goldfish_1           | {"time":"2017-06-23T06:00:52.379753509Z","remote_ip":"172.19.0.1","host":"localhost","method":"GET","uri":"/api/health","status":200, "latency":2783,"latency_human":"2.783979ms","bytes_in":0,"bytes_out":225}
goldfish-frontend_1  | 172.19.0.1 - - [23/Jun/2017:06:00:52 +0000] "GET /api/health HTTP/1.1" 200 225 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4" "-"
```

### CODE REVIEW

**Comment by Caiyeon** [comment]
Looks good, thanks! I've been wanting to find the time to get a docker compose file going, this looks like what I wanted to achieve. I'm also a fan of being able to set the release version to fetch.

Thanks for testing too. Once I get a chance to take this for a spin myself, if everything looks good, I'll merge it in.

Cheers

**Comment by Caiyeon** [comment]
I can't seem to logon after docker compose. `Goldfish could not use transit key`

Also, I can't guarantee that I'll keep the nginx part of this compose after merging. It's unfair to assume that people wanting to take the docker stack for a spin will want the extra complexity

**Comment by ecliptik** [comment]
@Caiyeon hopefully can look at this today. I didn't realize the transit key wasn't working. When I set this up to deploy to our Rancher clusters I was having more issues with it connecting to our Vault EC@ instance (that TLS disable logic fix from a few weeks ago) and thought it was working since Vault info was showing up in the info screen.

I added the Nginx service since I was already using it for our Goldfish/Vault Rancher/AWS deployments, and it made more sense to break out the static assets into a container specifically designed to serve in our production environment instead of running multiple processes within the same container.

BTW, here is a basic compose file to deploy to Rancher if anyone is interested. This assumes that `vault` is running elsewhere (on an EC2 instance for our case) and the `config.hcl` has the necessary options set. The `.env.export` contains the `${VAULT_TOKEN}` generated from transit when the deploy job is ran. We've had this running for the last few weeks and it works well deploying via Jenkins. We put an AWS ELB in front of the containers and forward 80/443 -> 32000 with SSL termination for the actual endpoint we use.

```
version: '2'
services:
  goldfish:
    image: ${ORG}/goldfish
    env_file:
      - .env.export
    stdin_open: true
    command: /app/goldfish -config=/app/config.hcl -token=${VAULT_TOKEN}
  goldfish-frontend:
    image: ${ORG}/goldfish:frontend
    ports:
      - 32000:80/tcp
    stdin_open: true
```

**Comment by checksrc** [comment]
Nice @ecliptik - I assume the images your using are just the ones you've commited in this PR? I.e. frontend/backend ?

**Comment by ecliptik** [comment]
@checksrc yes, the `${ORG}/goldfish` and `${ORG}/goldfish:frontend` images were built from the `Dockerfile.frontend` and `Dockerfile.backend` files in this PR respectively and we are running them via [Rancher](https://github.com/rancher/rancher) and they in turn connect to Vault running on an EC2 instance for air-gap purposes.

Since `config.hcl` is environment specific and included in the image they are in a private org repository on Docker Hub. If the config had the option to be managed via environment variables (ala [12 Factor](https://12factor.net/config)) the images could be environment agnostic.

It makes sense to use a `.hcl` in the context of Goldfish since it is adhering to Hashicorp best practices, and in place of environment variables you could us something like [confd](https://github.com/kelseyhightower/confd) to template out a config for different deployment environments.

Maybe I should mark this PR for more of a "production" level deployment instead of for development since it's commits are more designed to run via orchestration instead of a dev level (hence the nginx part).

Originally this PR was tested locally with just `docker-compose`, but with a few small changes it can run in Rancher Cattle or Docker Swarm. Using it as a base someone could probably write up a Kubernetes config as well since the images themselves should be orchestration agnostic.

**Comment by Caiyeon** [comment]
The compose file itself looks good in structure, I just can't guarantee that I will keep the nginx portion. Goldfish process itself serves the static html folder anyway, so I'm not seeing any benefit other than in a specialized environment.

Also I would usually leave orchestration to something like terraform, which reminds me I should make a goldfish terraform module...

**Comment by checksrc** [comment]
@Caiyeon Hey, is this still an in focus item?

**Comment by Caiyeon** [comment]
@checksrc Not sure what you mean. I would like to have a docker compose. If you wish to contribute, please open your own pull request.

**Comment by ecliptik** [comment]
I finally got around to taking a look at this again and saw that with v0.5.0 assets are now included and there is no longer a need for a static nginx container.

Updated PR now works with just a single Goldfish container and uses the upstream Vault container. This is similar to a Production Deployment and marked this in the README-compose.md.

Fixed up the transit token issue and logins with the default vault root token now work properly.

**Comment by Caiyeon** [comment]
Yes, the assets being separate had a lot of minor inconveniences, all of which should be resolved with a single binary release.

This is looking really good! I hope I'm able to find some time to test this soon

**Comment by Caiyeon** [comment]
Works well! Thanks for the contribution!

**Pull request merged**
