### PR TITLE
Functional RADIUS support

### PR DESCRIPTION
**Pull request by isugimpy**
As described in https://github.com/Caiyeon/goldfish/issues/221 I have implemented RADIUS support.  In my limited testing, it seems to work well.  The tokens generated from a RADIUS auth appear on the Users page under Tokens, the permissions I set on my user object seem to work just fine.  The only unfortunate thing I'm seeing at this point is that there's no way to manage RADIUS users from the UI, which may end up being a headache, but I may be able to come back and write a patch for that later.

### CODE REVIEW

**Comment by isugimpy** [comment]
I just realized, there was no point in writing integration tests.  They're going to fail, and I know it, because there's no way for it to actually test RADIUS auth.  I'm going to remove the tests.

**Comment by isugimpy** [comment]
@Caiyeon Ready for your review.  If you have any suggestions on how I could reasonably mock out the RADIUS auth in a way that could provide a meaningful test, I'd love to hear it, but otherwise I think this is good to go for a merge.

**Comment by Caiyeon** [comment]
Spinning up a local radius server should provide decent grounds for integration tests

https://github.com/layeh/radius

**Comment by isugimpy** [comment]
I've gotten crazy busy and didn't have time to implement tests for this.  Rather than leave it hanging indefinitely, I'm going to close this, and circle back when I can.

**Pull request closed without merging**
