### PR TITLE
Added mlock memory protection

### PR DESCRIPTION
**Pull request by Albibek**
Hi. 

Since, Godfish's server does secret processing, the memoryh security is required for them to be safe.

This PR adds Vault-like memory protection along with corresponding option to disable it.
Also some small fixes (forgotten value in formatted strings) are done.

### CODE REVIEW

**Comment by Caiyeon** [comment]
Have you tested this:
1. On windows?
2. On dev and non-dev modes?

In addition, vault's helper package simply return nil if mlock is not supported on the operating system. This is ok on vault because their launchup notifies the user whether mlock is on or off. Goldfish has no such method at the moment.

Deployment scripts in vagrant and docker would also have to be updated to set mlock capability on the executable.

**Comment by Albibek** [comment]
Afaik, mlock is unix-only syscall requiring root privileges. I've only did existing tests.

We can change it to handle the error gracefully if you like: just continue working giving warning. 
Would this be OK?

**Comment by Caiyeon** [comment]
Yes, it is indeed a unix-only syscall, but how are you sure the code won't break things on windows?
In addition, this causes changes to the deployment steps. Deployment changes can only be made in major version bumps (i.e. 0.5.x to 0.6.0)
As I mentioned earlier there is no graceful method for goldfish to alert the user whether mlock is available/on/off

I think we'll have to shelf this for now. I want the functionality, but it will have to come in a later major update, and more thorough testing would need to be done. In particular, this would break docker compose and vagrant.

I will update the string formatting for the next minor update. I can't pull just those changes in without the mlock, otherwise I would merge just that.

**Comment by Albibek** [comment]
The code shouldn't break windows unless the options is on. I've copied this behaviour from the original Vault itself because of the same security level requirements. It doesn't seem to break anything when the option is turned off, but we can do sdditionl checks to skip it on non-unix without even trying to set mlock on.

**Comment by Albibek** [comment]
Added mlock to only work on linux/darwin (Go only supports mlock on those OS currently)

**Comment by Caiyeon** [comment]
v0.6.0 will be the next release, so deployment workflow breaking changes can be integrated. I'll be reviewing this soon. You'll very likely see this in v0.6.0

**Comment by Caiyeon** [comment]
Merged. You should see this in v0.6.0

Thanks for the patch

**Pull request merged**
