### PR TITLE
Allow CA Cert+Path and Client Cert+Key for Vault in Goldfish config file

### PR DESCRIPTION
**Pull request by sircinnamon**
This allows passing in options from the goldfish config through to the eventual vault client config, which allows goldfish to communicate using TLS to a vault with a custom certificate authority.

### CODE REVIEW

**Comment by Caiyeon** [comment]
Custom CA is something that should be implemented. However, regarding custom client certs: I've thought about (and even implemented) client certs, only to realize that this meant everyone visiting goldfish would be using goldfish's certificates. If operators make the assumption that people must have certs to talk to vault, this assumption is then ambiguous, since people can now use goldfish's cert to bypass this (sort of).

What is your reasoning for implementing client certs?

**Comment by sircinnamon** [comment]
Enforcing a client cert is a desirable security measure, even if anyone can access goldfish. The permissions of goldfish can be limited and therefore it can shield vault. Ensuring communication between goldfish and vault is as secure as possible is also desirable.  I can also see there being a desire to limit how users can interact with vault to be strictly through goldfish (for logging purposes etc.)  and only allowing vault to trust a very limited range of client certs including the one goldfish uses.

Potentially existing vault setups already require a client cert and that may prevent developers from using goldfish. Also, perhaps (at least while goldfish is in development) the features goldfish provides are safe to access through goldfish but other features (certificate management) must be handled on the CLI or HTTP API, and the administrator may desire those actions be secured with a client cert. 

Those arguments aside, my reasoning was mostly that there isn't much of a downside to adding it. With this change the decision is up to the user who configures goldfish, as the field is fully optional.

**Comment by Caiyeon** [comment]
Limiting goldfish permissions have no effect on what users can do to vault through goldfish. My concern is that operators can misunderstand this configuration, and not realize that by setting client certs, they're giving everyone the rights to use that cert. Then, setting client cert requirements in vault-side is meaningless.

**Comment by sircinnamon** [comment]
Clear documentation of the configuration could prevent any misunderstanding. Restricted access to the server hosting goldfish would mean that not _anyone_ could use that cert.

**Comment by ewdurbin** [comment]
Any chance of seeing this PR broken up into the Custom CA part and the Client Certs part? Sounds like there is no opposition to being able to supply a custom Certificate Authority configuration.

**Comment by sircinnamon** [comment]
Created PR #220 containing only the server CA components. However I am still in favour of adding the client side certs.

**Comment by Caiyeon** [comment]
#220 has been merged. I have no plans on implementation client certificates in the near future, so I'm closing this PR

**Comment by adragoset** [comment]
So no support for vault client certs for the forseeable future. I guess i need to find a different vault ui because right now my deployment of vault requires client certificates along with acl tokens. Ive been waiting months for this and the only part that actually mattered wasnt merged into the latest version.

**Comment by Caiyeon** [comment]
Hi there @adragoset,

Indeed, the client cert feature will not be implemented in the foreseeable future. Goldfish is a software project I released in hopes of it being useful, and I owe nothing to anyone in terms of what to implement. 

If you need a ui with more support and liability, the enterprise ui may fit your needs better. Support HashiCorp!

Alternatively, Goldfish's MPL2 license is quite permissive. You are more than welcome to make changes as needed.

**Pull request closed without merging**
