### PR TITLE
Added docker-compose.yml

### PR DESCRIPTION
**Pull request by checksrc**
In order for the compose I've created to work a docker image will have to built for goldfish that omits the vault content and runs goldfish only. Happy to help with that if required. The compose script may need tweaking with regards to the goldfish service in order to pass it any information it needs about the vault container. 

The ideal scenario is for the entire goldfish repo to contain the goldfish content only. 
The containers would then both be kept in line with specific versions of vault and goldfish respectively - this means that vault could be kept updated in line with the official vault docker image, and goldfish can be designed to work for non docker users by simply doing a git clone on the required content. 

Does that make sense? Realise it's possibly a big ask to cut vault content out. 
Happy to help with any docker related stuff here.

### CODE REVIEW

**Comment by checksrc** [comment]
Aha! Only just noticed PR #87 . This gives me something to build upon.

**Comment by Caiyeon** [comment]
It makes more sense for vault to be left out of the compose. Ideally, a stack would compose of a vault image, and a goldfish image that is bootstrapped to that vault instance. The hard part is how to prepare vault with the required data in order for goldfish to be bootstrapped. Certificates can be omitted with a proper goldfish config file.

**Comment by checksrc** [comment]
I think you could provide two options - because alot of people that are new to vault might need to set an instance up anyway. In addition, based on a compose that has both a vault container and a goldfish container, people can adapt that for their own set up if they have vault there already. What you're describing is a bit over complicated because it's tricky to anticipate what an end user has set up.

A compose that uses shared data between containers is easy to set up, if you know the data that needs to be shared.

This is defined as (use rw for read-write to allow the container to write to the host dir, or ro to allow to container to read only from the host dir).

volumes:
  - /dir/on/host:/dir/on/container:rw/ro

For example, for the vault file backend;
```
  volumes:
    - /srv/vault/file:/vault/file:rw
```

You can attach multiple volumes to multiple containers, just by using the same host dir.

**Comment by Caiyeon** [comment]
I'm not sure how sharing volumes relate to the problem. The problem is that a docker compose needs to initialize vault according to steps 1 & 2 [here](https://github.com/Caiyeon/goldfish/wiki/Production-Deployment)

PR #87 handles this part, but it doesn't work fully and uses nginx rather than goldfish's static serve

**Comment by checksrc** [comment]
Ah I see what you mean now - I'll look into it

**Pull request closed without merging**
